--- #YAML:1.0
name:               HTTP-Response-CGI
version:            1.0
abstract:           HTTP style response message, from CGI output
author:
    - Ken Dreyer <ktdreyer@ktdreyer.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Response:  ~
resources:
    homepage:  http://www.ktdreyer.com
    license:   http://dev.perl.org/licenses/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
